[simulation]
nions = 10000
nions_update = 100
rng_seed = 12345
workdir = "./"

[beam]
symbol = "B"
name = "Boron"
Z = 5
M = 11.009
energy = 50.0
tilt = 0.0

[layers]
name = ["Layer 1"]
width = [4000.0]
density = [0.04994]
compound_correction = [1.0]
gas = [false]

[[layers.material]]
symbol = ["Si"]
name = ["Silicon"]
Z = [14]
M = [28.086]
stoichiometry = [1]
displacement_energy = [15.0]

[models]
potential = "ZBL"
electronic_stopping = "Lindhard"

[models.scattering_integrals]
algorithm = "magic"
n_absc = 4

[models.Lindhard_correction]
"B->Si" = 1.5
"Si->Si" = 1.0

[output.trajectories]
start = false
end = false
collisions = false

[output.depth_distribution]
nbins = 40
limits = [0.0, 4000.0]
ion_recoils = true
phonons = false
ionization = false

[output.lateral_distribution]
nbins = 40
limits = [-2000.0, 2000.0]
ion_recoils = true
phonons = false
ionization = false

[output.backscattered_atoms_distribution.energy]
nbins = 40
limits = [0.0, 50.0]

[output.backscattered_atoms_distribution.angle]
nbins = 40
limits = [-90.0, 90.0]

[output.transmitted_atoms_distribution.energy]
nbins = 40
limits = [0.0, 50.0]

[output.transmitted_atoms_distribution.angle]
nbins = 40
limits = [-90.0, 90.0]
